"""
installers/common/env_writer.py — Safe Environment File Writer
Synthos · shared installer helper

Writes .env files with these guarantees:
  - Existing files are NEVER silently overwritten
  - A timestamped backup is created before any write
  - Writes are atomic (temp file → rename)
  - File permissions are set to 600 after write
  - No secret values are logged at any level

Rules enforced:
  - If the target path exists → backup first, then write
  - If write fails → backup is preserved, original is untouched
  - chmod 600 always applied after successful write
"""

import logging
import os
import shutil
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

log = logging.getLogger("installer.env_writer")


def _backup_existing(env_path: Path) -> Optional[Path]:
    """
    Copy existing env file to a timestamped backup.
    Returns the backup path, or None if no existing file.
    """
    if not env_path.exists():
        return None
    ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    backup_path = env_path.with_name(f".env.backup_{ts}")
    shutil.copy2(env_path, backup_path)
    os.chmod(backup_path, 0o600)
    log.info("Existing .env backed up to %s", backup_path.name)
    return backup_path


def write_env(env_path: Path, content: str) -> Path:
    """
    Write env content to env_path atomically.

    - If file exists: backs up first, then writes
    - Uses temp file + rename for atomicity
    - Sets chmod 600 on result
    - Returns final path

    Raises:
        OSError: if write or rename fails (backup preserved if applicable)
    """
    # Ensure parent directory exists
    env_path.parent.mkdir(parents=True, exist_ok=True)

    # Backup existing file
    backup = _backup_existing(env_path)

    tmp_path = env_path.with_name(".env.tmp")
    try:
        tmp_path.write_text(content, encoding="utf-8")
        tmp_path.replace(env_path)
        os.chmod(env_path, 0o600)
        log.info("Wrote %s (%d bytes, chmod 600)", env_path, env_path.stat().st_size)
    except OSError as exc:
        log.error("Failed to write env file: %s", exc)
        # Clean up temp if it exists
        if tmp_path.exists():
            tmp_path.unlink(missing_ok=True)
        raise

    return env_path


def build_retail_env(config: dict, generated_secret_key: str) -> str:
    """
    Build the .env file content for a retail node.
    All values come from config dict (collected by wizard).
    PORTAL_SECRET_KEY is generated externally and passed in.
    Returns the full file content as a string.
    """
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    lines = [
        f"# Synthos Retail Node — Environment Configuration",
        f"# Generated by install_retail.py on {now}",
        f"# DO NOT SHARE — contains private API keys",
        f"# chmod 600 enforced by installer",
        f"",
        f"# ── CORE API KEYS ─────────────────────────────────────────────",
        f"ANTHROPIC_API_KEY={config.get('anthropic_key', '')}",
        f"ALPACA_API_KEY={config.get('alpaca_key', '')}",
        f"ALPACA_SECRET_KEY={config.get('alpaca_secret', '')}",
        f"ALPACA_BASE_URL={config.get('alpaca_base_url', 'https://paper-api.alpaca.markets')}",
        f"TRADING_MODE={config.get('trading_mode', 'PAPER')}",
        f"CONGRESS_API_KEY={config.get('congress_key', '')}",
        f"",
        f"# ── OPERATING MODE ────────────────────────────────────────────",
        f"OPERATING_MODE={config.get('operating_mode', 'SUPERVISED')}",
        f"AUTONOMOUS_UNLOCK_KEY={config.get('autonomous_unlock_key', '')}",
        f"",
        f"# ── LICENSE ───────────────────────────────────────────────────",
        f"LICENSE_KEY={config.get('license_key', '')}",
        f"",
        f"# ── SYSTEM IDENTITY ───────────────────────────────────────────",
        f"PI_ID={config.get('pi_id', 'synthos-pi-1')}",
        f"PI_LABEL={config.get('pi_label', '')}",
        f"PI_EMAIL={config.get('pi_email', '')}",
        f"OWNER_NAME={config.get('owner_name', '')}",
        f"OWNER_EMAIL={config.get('owner_email', '')}",
        f"STARTING_CAPITAL={config.get('starting_capital', '100')}",
        f"SUPPORT_EMAIL={config.get('support_email', 'synthos.signal@gmail.com')}",
        f"",
        f"# ── PORTAL ────────────────────────────────────────────────────",
        f"PORTAL_PORT={config.get('portal_port', '5001')}",
        f"PORTAL_PASSWORD={config.get('portal_password', '')}",
        f"PORTAL_SECRET_KEY={generated_secret_key}",
        f"",
        f"# ── MONITOR / DEAD MAN SWITCH ─────────────────────────────────",
        f"MONITOR_URL={config.get('monitor_url', '')}",
        f"MONITOR_TOKEN={config.get('monitor_token', 'changeme')}",
        f"",
        f"# ── ALERTS (SENDGRID) ─────────────────────────────────────────",
        f"SENDGRID_API_KEY={config.get('sendgrid_key', '')}",
        f"ALERT_FROM={config.get('alert_from', '')}",
        f"USER_EMAIL={config.get('user_email', '')}",
        f"",
        f"# ── SMS ALERTS (GMAIL GATEWAY) ────────────────────────────────",
        f"GMAIL_USER={config.get('gmail_user', '')}",
        f"GMAIL_APP_PASSWORD={config.get('gmail_app_password', '')}",
        f"ALERT_PHONE={config.get('alert_phone', '')}",
        f"CARRIER_GATEWAY={config.get('carrier_gateway', 'tmomail.net')}",
        f"",
        f"# ── PORTAL ADVANCED SETTINGS (written by portal /api/settings) ─",
        f"CLOSE_SESSION_MODE=conservative",
        f"MAX_POSITION_PCT=0.10",
        f"MAX_SECTOR_PCT=25",
        f"",
        f"# ── GITHUB (optional — for sync.py) ──────────────────────────",
        f"GITHUB_TOKEN={config.get('github_token', '')}",
        f"",
    ]
    return "\n".join(lines)


def build_company_env(config: dict, db_path: str) -> str:
    """
    Build the env file content for a company node.
    COMPANY_MODE=true is always written — no license checks on company Pi.
    Returns the full file content as a string.
    """
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    lines = [
        f"# Synthos Company Node — Environment Configuration",
        f"# Generated by install_company.py on {now}",
        f"# DO NOT SHARE — contains company secrets",
        f"# chmod 600 enforced by installer",
        f"",
        f"# ── NODE TYPE ─────────────────────────────────────────────────",
        f"COMPANY_MODE=true",
        f"",
        f"# ── DATABASE ──────────────────────────────────────────────────",
        f"DATABASE_PATH={db_path}",
        f"",
        f"# ── SENDGRID (Scoop delivery) ─────────────────────────────────",
        f"SENDGRID_API_KEY={config.get('sendgrid_key', '')}",
        f"SENDGRID_FROM={config.get('sendgrid_from', '')}",
        f"OPERATOR_EMAIL={config.get('operator_email', '')}",
        f"",
        f"# ── LICENSE KEY INFRASTRUCTURE ────────────────────────────────",
        f"KEY_SIGNING_SECRET={config.get('key_signing_secret', '')}",
        f"VAULT_URL={config.get('vault_url', '')}",
        f"",
        f"# ── SERVICE PORTS ─────────────────────────────────────────────",
        f"COMMAND_PORT={config.get('command_port', '5002')}",
        f"INSTALLER_PORT={config.get('installer_port', '5003')}",
        f"HEARTBEAT_PORT={config.get('heartbeat_port', '5004')}",
        f"",
        f"# ── SCHEDULER ─────────────────────────────────────────────────",
        f"SCHEDULER_TIMEOUT_SEC={config.get('scheduler_timeout', '120')}",
        f"MARKET_HOURS_START={config.get('market_hours_start', '0930')}",
        f"MARKET_HOURS_END={config.get('market_hours_end', '1600')}",
        f"MARKET_TIMEZONE={config.get('market_timezone', 'US/Eastern')}",
        f"",
        f"# ── GITHUB ────────────────────────────────────────────────────",
        f"GITHUB_TOKEN={config.get('github_token', '')}",
        f"GITHUB_REPO={config.get('github_repo', '')}",
        f"",
    ]
    return "\n".join(lines)
